theme: jekyll-theme-minimal
title: WEHI Research Computing Platform
description: Public page for the WEHI Research Computing Platform (RCP)
logo: https://wehi-researchcomputing.github.io/assets/rcp_logo.png
